config/routes.rb
Recordstack::Application.routes.draw do
  resources :albums

  root 'stacks#index'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/stacks/search/', to: 'stacks#search', via: 'post'
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :stack

	def index
	end

	def create
		@album = current_user.albums.build(album_params)
		if @album.save
			flash[:success] = "Nice."
			redirect_to root_url
		else
			render 'stacks/home'
		end
	end

	def destroy
	end 

	private

		def album_params
			params.require(:album).permit(:album)
		end
end

app/models/discogs_search.rb
require 'rubygems'
require 'httparty'

class DiscogsSearch
	include HTTParty
	base_uri 'api.discogs.com'
	default_params :output => 'json'
	format :json

	def self.search_album(album)
		get('/releases/', :query => {:album => album})
	end

end

app/models/stack.rb
class Stack < ActiveRecord::Base
	belongs_to :user
	has_many :albums
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_many :stacks
  has_many :albums, through: :stacks
  #Virtual attribute for authenticating by either username or email
  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
  	conditions = warden_conditions.dup
  	if login = conditions.delete(:login)
  	  # when allowing distinct User records with, e.g., "username" and "UserName"...
	  where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
  	else
  		where(conditions).first
  	end
  end
end

app/controllers/application_controller.rb
require 'httparty'
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  include HTTParty
  headers 'User-Agent' => 'RecordStackBacklogs/0.1'
  base_uri 'http://musicbrainz.org/ws/2/'
  format :json

  def search
    response = get('/release-group/', :query => {:album => album})
    data = JSON.parse(response.body)
    @release = data['query']['results']
  end

  #def index
    #choose the URL to visit
   # @app_url = params[:url] || "http://musicbrainz.org/ws/2/"
    #ensure it starts with http
    #@app_url = "http://#{@app_url}" unless @app_url.starts_with?("http")

    #begin
      #retrieve the search
    #end
  # end

  def devise_parameter_sanitizer
  	if resource_class == User
  		User::ParameterSanitizer.new(User, :user, params)
  	else
  		super
  	end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

		def sign_up_params
			allow = [:username, :email, :password, :password_confirmation, :remember_me]
			params.require(resource_name).permit(allow)
		end
		
end

app/controllers/stacks_controller.rb
require 'rubygems'
# require 'HTTParty'
require 'Nokogiri'

class StacksController < ApplicationController
	include HTTParty
	headers 'User-Agent' => 'RecordStackBacklogs/0.1'
	base_uri 'http://musicbrainz.org/ws/2/'
	format :json
	def all
		render json: Stacks.order_by(:name, :asc)
	end

	def index

	end

	def show
		@stacks = Stack.find_by(id: params[:id])
		if @stack = nil?
			@stack = Stack.all
			redirect_to action: :index
		end
	end

	def search
		@resmbid = {}

		mburl = "http://musicbrainz.org/ws/2/release-group/" # musicbrainz url
		caurl = "http://coverartarchive.org/release-group/" # coverartarchive url
		lookup = params[:lookup]
		response = HTTParty.get(mburl, :query => {"query" => lookup, "releasegroup" => "Sunbather"})
		xml_data = response.body
		doc = Nokogiri::XML(xml_data)
		@artist = doc.css('artist-credit > name-credit > artist > name').collect {|artist| artist.text.strip}
		@results = doc.css('release-group > title').collect {|title| title.text.strip}
		@mbid = doc.xpath("//@id").collect {|mbid| mbid.text.strip}
		@results.each_with_index do |value, index|
			@resmbid[value] = @mbid[index]
		end
		@coverart = @mbid.first
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  helper StacksHelper

  def about
  end

  def contact
  end

  def help
  end

  def home
  	@stack = Stack.new
  	@album = Album.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:edit, :update]
	before_action :correct_user, only: [:edit, :update]
	before_action :admin_user, only: :destroy

	def index
		@users = User.paginate(page: params[:page])
	end

	def show
		@user = User.find(params[:id] || [:username])
		
		respond_to do |format|
			format.html # show.html.erb
			format.xml { render :xml => @user }
		end
	end

	def update
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		# Before filters

		def admin_user
			redirect_to(root_url) unless current_user?(@user)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stacks_helper.rb
module StacksHelper
  def search
	  response = get('/release-group/', :query => {:album => album})
	  data = JSON.parse(response.body)
	  @release = data['query']['results']
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<p>A simple project by <a href="http://www.andrewventura.com/">Andrew Ventura</a></p>
	</small>
	<nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Help", help_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RecordStack", root_path, { :class=>"navbar-brand" } %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a class = class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'View profile', '#', :class => 'navbar-link' %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recordstack</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		<%=render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/stacks/_dash.html.erb
<%= provide(:title, 'Dashboard') %>

<h2>Welcome, <%= current_user.username %>!</h2>
<br />
	<%= form_tag "stacks/search" do %>
		<label for="lookup">Search for a record</label>
			<%= text_field_tag :lookup %>
			<%= submit_tag "Submit" %>
		<% end %>

app/views/stacks/_stack_list.html.erb
<div class="container">
	<h2>Your Stack</h2>
</div>

app/views/stacks/index.html.erb
<% provide(:title, "Home") %>
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<%= render 'dash' %>
		</div>
		<div class="col-md-9">
			<%= render 'stack_list' %>
		</div>
	</div>
</div>

app/views/stacks/search.html.erb
Hooray! You searched for something!<br />
<h4>Albums matching "<%= params[:lookup] %>":</h4>
<br />
<br />
<br />
<div class="search-result container">
<!--<ul style="list-style-type: none;">
	<%= @results.each do |a| %>
		<li><%= link_to a, "http://www.musicbrainz.org/release-group/", { :class => "searchresults" } %></li>
	<% end %>
</ul> -->
<ul style="list-style-type: none; display: block;"`>
	<%= @resmbid.each do |hash, key| %>
		<li style="display: inline-block; padding: 8px 8px;" class="text-center">
			<%= link_to image_tag("http://www.coverartarchive.org/release-group/#{key}/front", size: "200x200"), "http://www.musicbrainz.org/release-group/#{key}" %>
			<br />
			<strong><%= link_to hash, "http://www.musicbrainz.org/release-group/#{key}", { :class => "searchresults" } %></strong>
			<br />
			
			<%= link_to "#{@artist.first}", "http://www.musicbrainz.org/artist/#{key}" %>
			<br />
			<button class="btn text-center" style="margin: 5px 0" type="button">
				<span class="glyphicon glyphicon-plus"></span> Add To Stack <!-- this will eventually save the album to the album model -->
			</button>	
		</li>
	<% end %>
	<br />
	<br />
	<br />
	<br />
	<hr>
<!-- <%= link_to image_tag("http://www.coverartarchive.org/release-group/#{@mbid.first}/front", size: "250x250"), "http://www.musicbrainz.org/release-group/#{@mbid.first}" %> -->

</div>

app/views/static_pages/_dash.html.erb
<%= provide(:title, 'Dashboard') %>

<h1>Dashboard</h1>
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<h2>Welcome, <%= current_user.username %>!</h2>
			<br />
			<p>Search for an item</p>
			<%= @release %>
		</div>
		<div class="col-md-9">
			<h2>Your Stacks</h2>
		</div>
	</div>
</div>

app/views/static_pages/_intro.html.erb
<div class="center hero-unit">
	<h1>RecordStack</h1>
	<h2>RecordStack is a service that lets you track and remember albums you want to listen to but haven't got around to yet.</h2>
	<%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-large btn-primary" %>
	<br />
	<br />
	<%= link_to "Login", new_user_session_path, class: "small" %>
</div>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>RecordStack (working title) is a project that hopes to help you get around to listening to new/old music you've been putting off.</p>


<h2>Credits</h2>
<p>Recordstack is run by <a href="http://www.andrewventura.com/">Andrew Ventura</a>, a newbie rails dev who wanted something to work on. It's a labor of love. Kind of.</p>
<p>Thanks to these web services for letting me awkwardly and repeatedly request info on Deafheaven's <a href="http://deafheavens.bandcamp.com/album/sunbather">"Sunbather"</a> from their databases during development and testing:</p>
<blockquote><small>MusicBrainz, EchoNest, Discogs, Last.FM, 7Digital, Amazon Web Services</small></blockquote>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>Have a suggestion/scathing critique? Here's how you can yell at me about it.</p>
<p>Contribute to the project at <a href="http://www.github.com/andrewventura/recordstack">GitHub</a></p>
<p>Send me an email <a href="mailto:andrew@andrewventura.com">here</a> and let your freak flag fly.</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>Not a lawyer or a licensed psychologist, so the scope of my help is kinda limited. But if you have problems that you need help with related to this app, well, okay. Tough.</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Welcome!') %>
<% if signed_in? %>
	<%= render 'dash' %>
<% else %>
	<%= render 'intro' %>
<% end %>

app/views/users/_users.html.erb
<%= @user. %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>Users</h1>
<%= @users.all %>

app/views/users/show.html.erb
<%= @user.username %><br />
<%= @user.favoritealbum %>